<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

    <?php
        $themes = FreshRSS_Themes::get();
        $lightTheme = FreshRSS_Context::$user_conf->light_theme;
        $darkTheme = FreshRSS_Context::$user_conf->dark_theme;
    ?>

    <div class="form-group">
        <label class="group-name" for="light_theme"><?= _t('ext.sync_with_system_theme.light_theme') ?></label>
        <div class="group-controls">
            <select name="light_theme" required="" data-leave-validation="<?= $lightTheme ?>">
                <option value="null" <?= $light_theme === null ? 'selected="selected"' : '' ?>>
                    <?= _t('ext.sync_with_system_theme.not_set') ?>
                </option>
                <?php foreach($themes as $theme) { ?>
                    <option value="<?= $theme['id'] ?>" <?= $theme['id'] === $lightTheme ? 'selected="selected"' : '' ?>>
                        <?= $theme['name'] ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="group-name" for="dark_theme"><?= _t('ext.sync_with_system_theme.dark_theme') ?></label>
        <div class="group-controls">
            <select name="dark_theme" required="" data-leave-validation="<?= $darkTheme ?>">
                <option value="null" <?= $dark_theme === null ? 'selected="selected"' : '' ?>>
                    <?= _t('ext.sync_with_system_theme.not_set') ?>
                </option>
                <?php foreach($themes as $theme) { ?>
                    <option value="<?= $theme['id'] ?>" <?= $theme['id'] === $darkTheme ? 'selected="selected"' : '' ?>>
                        <?= $theme['name'] ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>

    <div class="form-group form-actions">
        <div class="group-controls">
            <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
            <button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
        </div>
    </div>
</form>
